const CB = 'https://icon.horse/icon/'

const protocols = [
  // SAFE
  {
    id: 'susds',
    name: 'sUSDS',
    tokenSymbol: 'sUSDS',
    protocol: 'Sky',
    network: 'Ethereum',
    asset: 'USDS',
    apy: 4.5,
    totalDeposits: '$5.0B',
    strategy: 'Deposit USDS into the Sky Savings Rate. Earns yield from protocol revenue automatically. No lockup, withdraw anytime. As safe as it gets in DeFi.',
    riskLevel: 'safe',
    logo: CB + 'sky.money',
    ethereumAddress: '0xa3931d71877C0E7a3148CB7Eb4463524FEc27fbD',
    llamaPoolId: 'd8c4eff5-c8a9-46fc-a888-057c4c668e72',
  },
  {
    id: 'jitosol',
    name: 'JitoSOL',
    tokenSymbol: 'JitoSOL',
    protocol: 'Jito',
    network: 'Solana',
    asset: 'SOL',
    apy: 7.2,
    totalDeposits: '$1.0B',
    strategy: 'Stake SOL with Jito and get JitoSOL back. Earns staking rewards plus MEV tips from Jito\'s validator network. Liquid — use it across Solana DeFi.',
    riskLevel: 'safe',
    logo: CB + 'jito.network',
    llamaPoolId: '0e7d0722-9054-4907-8593-567b353c0900',
  },
  {
    id: 'wsteth',
    name: 'wstETH',
    tokenSymbol: 'wstETH',
    protocol: 'Lido',
    network: 'Ethereum',
    asset: 'ETH',
    apy: 2.5,
    totalDeposits: '$18.7B',
    strategy: 'Stake ETH via Lido, wrap it as wstETH. Earns Ethereum staking rewards while staying liquid. Use as collateral in Aave, Morpho, and more.',
    riskLevel: 'safe',
    logo: CB + 'lido.fi',
    ethereumAddress: '0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0',
    llamaPoolId: '747c1d2a-c668-4682-b9f9-296708a3dd90',
  },
  {
    id: 'sdai',
    name: 'sDAI',
    tokenSymbol: 'sDAI',
    protocol: 'Sky',
    network: 'Ethereum',
    asset: 'DAI',
    apy: 3.5,
    totalDeposits: '$1.5B',
    strategy: 'Deposit DAI into the Sky Savings Rate. Your DAI grows automatically from protocol revenue. Battle-tested, fully redeemable, no lockup.',
    riskLevel: 'safe',
    logo: CB + 'sky.money',
    ethereumAddress: '0x83F20F44975D03b1b09e64809B757c47f942BEeA',
    llamaPoolId: 'c8a24fee-ec00-4f38-86c0-9f6daebc4225',
  },
  // LOW RISK
  {
    id: 'susde',
    name: 'sUSDe',
    tokenSymbol: 'sUSDe',
    protocol: 'Ethena',
    network: 'Ethereum',
    asset: 'USDe',
    apy: 10.5,
    totalDeposits: '$7.0B',
    strategy: 'Stake USDe to get sUSDe. Yield comes from ETH staking + funding rate arbitrage between spot and perps. Higher yield than pure stablecoins but relies on basis trade staying profitable.',
    riskLevel: 'low',
    logo: CB + 'ethena.fi',
    ethereumAddress: '0x9D39A5DE30e57443BfF2A8307A4256c8797A3497',
    llamaPoolId: '66985a81-9c51-46ca-9977-42b4fe7bc6df',
  },
  {
    id: 'wstusr',
    name: 'wstUSR',
    tokenSymbol: 'wstUSR',
    protocol: 'Resolv',
    network: 'Ethereum',
    asset: 'USR',
    apy: 6.5,
    totalDeposits: '$163M',
    strategy: 'Stake USR to earn yield from Resolv\'s delta-neutral strategy. Wrapped version (wstUSR) accrues value over time and is composable across DeFi.',
    riskLevel: 'low',
    logo: CB + 'resolv.xyz',
    ethereumAddress: '0x1202F5C7b4B9E47a1A484E8B270be34dbbC75055',
    llamaPoolId: '0aedb3f6-9298-49de-8bb0-2f611a4df784',
  },
  // HIGH YIELD
  {
    id: 'syrupusdc',
    name: 'SYRUPUSDC',
    tokenSymbol: 'SYRUPUSDC',
    protocol: 'Maple',
    network: 'Ethereum',
    asset: 'USDC',
    apy: 7.5,
    totalDeposits: '$2.1B',
    strategy: 'Lend USDC through Maple\'s Syrup pool to institutional borrowers. Higher yield because loans are undercollateralized — borrowers are vetted institutions. Syrup token rewards on top.',
    riskLevel: 'high-yield',
    logo: CB + 'maple.finance',
    ethereumAddress: '0x80ac24aA929eaF5013f6436cdA2a7ba190f5Cc0b',
    llamaPoolId: '43641cf5-a92e-416b-bce9-27113d3c0db6',
  },
  {
    id: 'rlp',
    name: 'RLP',
    tokenSymbol: 'RLP',
    protocol: 'Resolv',
    network: 'Ethereum',
    asset: 'USDC/USDT',
    apy: 40.0,
    totalDeposits: '$64M',
    strategy: 'Provide liquidity to Resolv\'s delta-neutral pools. Earn fees from rebalancing and protocol revenue. Exposed to smart contract risk and de-peg scenarios.',
    riskLevel: 'high-yield',
    logo: CB + 'resolv.xyz',
    ethereumAddress: '0x4956b52aE2fF65D74CA2d61207523288e4528f96',
    llamaPoolId: '2ad8497d-c855-4840-85ad-cdc536b92ced',
  },
  // SPECULATIVE
  {
    id: 'jlp',
    name: 'JLP',
    tokenSymbol: 'JLP',
    protocol: 'Jupiter',
    network: 'Solana',
    asset: 'SOL/ETH/BTC/USDC/USDT',
    apy: 15.0,
    totalDeposits: '$828M',
    strategy: 'Be the liquidity for Jupiter Perps. You hold a basket of SOL, ETH, BTC, and stables. Earn 75% of trading fees but take on trader PnL. High APY, volatile returns.',
    riskLevel: 'speculative',
    logo: 'https://static.jup.ag/jup/icon.png',
  },
  {
    id: 'onyc',
    name: 'ONyc',
    tokenSymbol: 'XCN',
    protocol: 'Onyx',
    network: 'Ethereum',
    asset: 'XCN',
    apy: 35.0,
    totalDeposits: '$49M',
    strategy: 'Stake XCN tokens in the Onyx protocol. Sky-high APY from token emissions — dilutive by nature. Only worth it if the token price holds up. Pure degen play.',
    riskLevel: 'speculative',
    logo: CB + 'onyxcoin.io',
    ethereumAddress: '0xA2cd3D43c775978A96BdBf12d733D5A1ED94fb18',
  },
  {
    id: 'prime',
    name: 'PRIME',
    tokenSymbol: 'PRIME',
    protocol: 'Echelon',
    network: 'Ethereum',
    asset: 'PRIME',
    apy: 38.0,
    totalDeposits: '$6.4M',
    strategy: 'Stake PRIME in Echelon\'s caching system to earn yield and in-game rewards. Returns depend on gaming ecosystem activity and PRIME token demand. High conviction play on crypto gaming.',
    riskLevel: 'speculative',
    logo: CB + 'echelon.io',
    ethereumAddress: '0xb23d80f5FefcDDaa212212F028021B41DEd428CF',
  },
]

export function getYieldProtocols(riskLevel) {
  if (!riskLevel) return protocols
  return protocols.filter(p => p.riskLevel === riskLevel)
}

export function getYieldById(id) {
  return protocols.find(p => p.id === id) || null
}
