import { PublicKey } from '@solana/web3.js'

const CB = 'https://logo.clearbit.com/'
const CI = 'https://cdn.jsdelivr.net/gh/spothq/cryptocurrency-icons@master/svg/color/'
const CG = 'https://coin-images.coingecko.com/coins/images/'

/**
 * SPL token list for portfolio balance reads.
 * mint: on-chain mint address (mainnet-beta)
 */
export const SPL_TOKEN_LIST = [
  // Crypto — Large Cap
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    logo: CI + 'btc.svg',
    decimals: 9,
    mint: new PublicKey('5XZw2LKTyrfvfiskJ78AMpackRjPcyCif1WhUsPDuVqQ'),
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    logo: CI + 'eth.svg',
    decimals: 9,
    mint: new PublicKey('7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs'),
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    logo: CI + 'bnb.svg',
    decimals: 9,
    mint: new PublicKey('9gP2kCy3wA1ctvYWQk75guqXuHfrEomqydHLtcTCqiLa'),
  },
  // Crypto — Mid Cap
  {
    symbol: 'UNI',
    name: 'Uniswap',
    logo: CI + 'uni.svg',
    decimals: 9,
    mint: new PublicKey('8FU95xFJhUUkyyCLU13HSzDLs7oC4QZdXQHL6SCeab36'),
  },
  {
    symbol: 'MNT',
    name: 'Mantle',
    logo: CB + 'mantle.xyz',
    decimals: 9,
    mint: new PublicKey('4SoQ8UkWfeDH47T56PA53CZCeW4KytYCiU65CwBWoJUt'),
  },
  // Crypto — Stables & Others
  {
    symbol: 'USDC',
    name: 'USD Coin',
    logo: CI + 'usdc.svg',
    decimals: 6,
    mint: new PublicKey('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'),
  },
  {
    symbol: 'USDT',
    name: 'Tether',
    logo: CI + 'usdt.svg',
    decimals: 6,
    mint: new PublicKey('Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB'),
  },
  {
    symbol: 'JUP',
    name: 'Jupiter',
    logo: 'https://static.jup.ag/jup/icon.png',
    decimals: 6,
    mint: new PublicKey('JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN'),
  },
  {
    symbol: 'RAY',
    name: 'Raydium',
    logo: CI + 'ray.svg',
    decimals: 6,
    mint: new PublicKey('4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R'),
  },
  {
    symbol: 'ORCA',
    name: 'Orca',
    logo: CI + 'orca.svg',
    decimals: 6,
    mint: new PublicKey('orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE'),
  },
  {
    symbol: 'BONK',
    name: 'Bonk',
    logo: 'https://arweave.net/hQiPZOsRZXGXBJd_82PhVdlM_hACsT_q6wqwf5cSY7I',
    decimals: 5,
    mint: new PublicKey('DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263'),
  },
  {
    symbol: 'PYTH',
    name: 'Pyth Network',
    logo: 'https://pyth.network/token.png',
    decimals: 6,
    mint: new PublicKey('HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3'),
  },
  {
    symbol: 'WSOL',
    name: 'Wrapped SOL',
    logo: CI + 'sol.svg',
    decimals: 9,
    mint: new PublicKey('So11111111111111111111111111111111111111112'),
  },
  {
    symbol: 'RENDER',
    name: 'Render',
    logo: CB + 'rendernetwork.com',
    decimals: 8,
    mint: new PublicKey('rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof'),
  },
  {
    symbol: 'TRUMP',
    name: 'Official Trump',
    logo: CG + '53746/large/trump.jpg',
    decimals: 6,
    mint: new PublicKey('6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN'),
  },
  {
    symbol: 'PUMP',
    name: 'Pump.fun',
    logo: CB + 'pump.fun',
    decimals: 6,
    mint: new PublicKey('pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn'),
  },
  // Forex stablecoins
  {
    symbol: 'PYUSD',
    name: 'PayPal USD',
    logo: CB + 'paypal.com',
    decimals: 6,
    mint: new PublicKey('2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo'),
  },
  {
    symbol: 'EURC',
    name: 'Euro Coin',
    logo: CB + 'circle.com',
    decimals: 6,
    mint: new PublicKey('HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr'),
  },
  {
    symbol: 'USDS',
    name: 'USDS',
    logo: CI + 'usdc.svg',
    decimals: 6,
    mint: new PublicKey('USDSwr9ApdHk5bvJKMjzff41FfuX8bSxdKcR81vTwcA'),
  },
  {
    symbol: 'USDP',
    name: 'Pax Dollar',
    logo: CB + 'paxos.com',
    decimals: 6,
    mint: new PublicKey('HVbpJAQGNpkgBaYBZQBR1t7yFdvaYVp2vCQQfKKEN4tM'),
  },
  {
    symbol: 'FDUSD',
    name: 'First Digital USD',
    logo: CB + 'firstdigitallabs.com',
    decimals: 6,
    mint: new PublicKey('9zNQRsGLjNKwCUU5Gq5LR8beUCPzQMVMqKAi3SSZh54u'),
  },
  {
    symbol: 'USDe',
    name: 'USDe',
    logo: CB + 'ethena.fi',
    decimals: 9,
    mint: new PublicKey('DEkqHyPN7GMRJ5cArtQFAWefqbZb33Hyf6s5iCwjEonT'),
  },
  {
    symbol: 'GYEN',
    name: 'GMO JPY',
    logo: CB + 'gmo.jp',
    decimals: 6,
    mint: new PublicKey('Crn4x1Y2HUKko7ox2EZMT6N2t2ZyH7eKtwkBGVnhEq1g'),
  },
  {
    symbol: 'VGBP',
    name: 'VNX British Pound',
    logo: CB + 'vnx.li',
    decimals: 9,
    mint: new PublicKey('5H4voZhzySsVvwVYDAKku8MZGuYBC7cXaBKDPW4YHWW1'),
  },
  {
    symbol: 'VCHF',
    name: 'VNX Swiss Franc',
    logo: CB + 'vnx.li',
    decimals: 9,
    mint: new PublicKey('AhhdRu5YZdjVkKR3wbnUDaymVQL2ucjMQ63sZ3LFHsch'),
  },
  {
    symbol: 'BRZ',
    name: 'Brazilian Digital Token',
    logo: CB + 'transfero.com',
    decimals: 4,
    mint: new PublicKey('FtgGSFADXBtroxq8VCausXRr2of47QBf5AS1NtZCu4GD'),
  },
  {
    symbol: 'TRYB',
    name: 'BiLira',
    logo: CB + 'bilira.co',
    decimals: 6,
    mint: new PublicKey('A94X2fRy3wydNShU4dRaDyap2UuoeWJGWyATtyp61WZf'),
  },
  {
    symbol: 'ZARP',
    name: 'ZARP Stablecoin',
    logo: CB + 'zfrancstablecoin.com',
    decimals: 6,
    mint: new PublicKey('dngKhBQM3BGvsDHKhrLnjvRKfY5Q7gEnYGToj9Lk8rk'),
  },
  // Yield tokens
  {
    symbol: 'JitoSOL',
    name: 'Jito Staked SOL',
    logo: CB + 'jito.network',
    decimals: 9,
    mint: new PublicKey('J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn'),
  },
  {
    symbol: 'JLP',
    name: 'Jupiter LP',
    logo: 'https://static.jup.ag/jup/icon.png',
    decimals: 6,
    mint: new PublicKey('27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4'),
  },
  // Commodities
  {
    symbol: 'PAXG',
    name: 'Gold',
    logo: CB + 'gold.org',
    decimals: 9,
    mint: new PublicKey('9TPL8droGJ7jThsq4momaoz6uhTcvX2SeMqipoPmNa8R'),
  },
  {
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    logo: CB + 'ssga.com',
    decimals: 9,
    mint: new PublicKey('hWfiw4mcxT8rnNFkk6fsCQSxoxgZ9yVhB6tyeVcondo'),
  },
  {
    symbol: 'SLV',
    name: 'iShares Silver Trust',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('iy11ytbSGcUnrjE6Lfv78TFqxKyUESfku1FugS9ondo'),
  },
  {
    symbol: 'USO',
    name: 'United States Oil Fund',
    logo: CB + 'uscfinvestments.com',
    decimals: 9,
    mint: new PublicKey('rpydAzWdCy85HEmoQkH5PVxYtDYQWjmLxgHHadxondo'),
  },
  {
    symbol: 'COPX',
    name: 'Global X Copper Miners ETF',
    logo: CB + 'globalxetfs.com',
    decimals: 9,
    mint: new PublicKey('X7j77hTmjZJbepkXXBcsEapM8qNgdfihkFj6CZ5ondo'),
  },
  {
    symbol: 'DBC',
    name: 'Invesco DB Commodity Index',
    logo: CB + 'invesco.com',
    decimals: 9,
    mint: new PublicKey('td1aY5AvYQuwGD75qNq9aPipMexraN9mQXJwqifondo'),
  },
  {
    symbol: 'FTGC',
    name: 'First Trust Global Tactical Commodity',
    logo: CB + 'ftportfolios.com',
    decimals: 9,
    mint: new PublicKey('ivBnfPTyuHDNWmMSnbavckhJK6SHZW8h77nZKsEondo'),
  },
  {
    symbol: 'IAU',
    name: 'iShares Gold Trust',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('M77ZvkZ8zW5udRbuJCbuwSwavRa7bGAZYMTwru8ondo'),
  },
  {
    symbol: 'NIKL',
    name: 'Sprott Nickel Miners ETF',
    logo: CB + 'sprott.com',
    decimals: 9,
    mint: new PublicKey('V8LRV7kWjrx6Prke9oHEHNUiR122BVtyuPciTCTondo'),
  },
  {
    symbol: 'PALL',
    name: 'abrdn Physical Palladium Shares ETF',
    logo: CB + 'abrdn.com',
    decimals: 9,
    mint: new PublicKey('P7hTXnKk2d2DyqWnefp5BSroE1qjjKpKxg9SxQqondo'),
  },
  {
    symbol: 'PDBC',
    name: 'Invesco Optimum Yield Diversified Commodity',
    logo: CB + 'invesco.com',
    decimals: 9,
    mint: new PublicKey('M6agiXbNgy8Xon9ngiW4ZDPbMFcNCTMkMMkshZyondo'),
  },
  {
    symbol: 'REMX',
    name: 'VanEck Rare Earth/Strategic Metals ETF',
    logo: CB + 'vaneck.com',
    decimals: 9,
    mint: new PublicKey('tiitb2Z1HtpB2DpVr6V7tdCFS3jmTinLeuGj9EVondo'),
  },
  // Stocks — Pre-IPO
  {
    symbol: 'OPENAI',
    name: 'OpenAI',
    logo: CB + 'openai.com',
    decimals: 9,
    mint: new PublicKey('PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF'),
  },
  {
    symbol: 'ANTH',
    name: 'Anthropic',
    logo: CB + 'anthropic.com',
    decimals: 9,
    mint: new PublicKey('Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw'),
  },
  {
    symbol: 'XAI',
    name: 'xAI',
    logo: CB + 'x.ai',
    decimals: 9,
    mint: new PublicKey('PreC1KtJ1sBPPqaeeqL6Qb15GTLCYVvyYEwxhdfTwfx'),
  },
  {
    symbol: 'SPACEX',
    name: 'SpaceX',
    logo: CB + 'spacex.com',
    decimals: 9,
    mint: new PublicKey('PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh'),
  },
  {
    symbol: 'POLY',
    name: 'Polymarket',
    logo: CB + 'polymarket.com',
    decimals: 9,
    mint: new PublicKey('Pre8AREmFPtoJFT8mQSXQLh56cwJmM7CFDRuoGBZiUP'),
  },
  // Stocks — Large Cap
  {
    symbol: 'SPY',
    name: 'S&P 500 ETF',
    logo: CB + 'ssga.com',
    decimals: 9,
    mint: new PublicKey('k18WJUULWheRkSpSquYGdNNmtuE2Vbw1hpuUi92ondo'),
  },
  {
    symbol: 'AAPL',
    name: 'Apple',
    logo: CB + 'apple.com',
    decimals: 9,
    mint: new PublicKey('XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp'),
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet',
    logo: CB + 'abc.xyz',
    decimals: 9,
    mint: new PublicKey('XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN'),
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft',
    logo: CB + 'microsoft.com',
    decimals: 9,
    mint: new PublicKey('XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX'),
  },
  {
    symbol: 'META',
    name: 'Meta',
    logo: CB + 'meta.com',
    decimals: 9,
    mint: new PublicKey('Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu'),
  },
  {
    symbol: 'TSLA',
    name: 'Tesla',
    logo: CB + 'tesla.com',
    decimals: 9,
    mint: new PublicKey('XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB'),
  },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co',
    logo: CB + 'jpmorganchase.com',
    decimals: 9,
    mint: new PublicKey('XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C'),
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA',
    logo: CB + 'nvidia.com',
    decimals: 9,
    mint: new PublicKey('Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh'),
  },
  {
    symbol: 'AMZN',
    name: 'Amazon',
    logo: CB + 'amazon.com',
    decimals: 9,
    mint: new PublicKey('Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg'),
  },
  {
    symbol: 'QQQ',
    name: 'Invesco QQQ ETF',
    logo: CB + 'invesco.com',
    decimals: 9,
    mint: new PublicKey('Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ'),
  },
  // Stocks — Mid Cap
  {
    symbol: 'MCD',
    name: "McDonald's Corp",
    logo: CB + 'mcdonalds.com',
    decimals: 9,
    mint: new PublicKey('XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2'),
  },
  {
    symbol: 'PEP',
    name: 'PepsiCo',
    logo: CB + 'pepsico.com',
    decimals: 9,
    mint: new PublicKey('gud6b3fYekjhMG5F818BALwbg2vt4JKoow59Md9ondo'),
  },
  {
    symbol: 'C',
    name: 'Citigroup',
    logo: CB + 'citigroup.com',
    decimals: 9,
    mint: new PublicKey('PjtfUiw6Hwd8PZ94EcUw8mBSYxp7SjjzSLeNTDKondo'),
  },
  {
    symbol: 'BA',
    name: 'Boeing',
    logo: CB + 'boeing.com',
    decimals: 9,
    mint: new PublicKey('1YVZ4LGpq8CAhpdpm3mgy7GgPb83gJczCpxLUQ3ondo'),
  },
  {
    symbol: 'COIN',
    name: 'Coinbase',
    logo: CB + 'coinbase.com',
    decimals: 9,
    mint: new PublicKey('Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu'),
  },
  {
    symbol: 'MSTR',
    name: 'MicroStrategy',
    logo: CB + 'microstrategy.com',
    decimals: 9,
    mint: new PublicKey('XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ'),
  },
  {
    symbol: 'CRCL',
    name: 'Circle',
    logo: CB + 'circle.com',
    decimals: 9,
    mint: new PublicKey('XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1'),
  },
  // Stocks — Small Cap
  {
    symbol: 'SBUX',
    name: 'Starbucks',
    logo: CB + 'starbucks.com',
    decimals: 9,
    mint: new PublicKey('iPFqjcZQTNMNXA4kbShbMhfAVD8yr8Uq9UtXMV6ondo'),
  },
  {
    symbol: 'ADBE',
    name: 'Adobe',
    logo: CB + 'adobe.com',
    decimals: 9,
    mint: new PublicKey('12Rh6JhfW4X5fKP16bbUdb4pcVCKDHFB48x8GG33ondo'),
  },
  {
    symbol: 'INTU',
    name: 'Intuit',
    logo: CB + 'intuit.com',
    decimals: 9,
    mint: new PublicKey('CozoH5HBTyyeYSQxHcWpGzd4Sq5XBaKzBzvTtN3ondo'),
  },
  // ETF
  {
    symbol: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('CqW2pd6dCPG9xKZfAsTovzDsMmAGKJSDBNcwM96ondo'),
  },
  {
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('dvj2kKFSyjpnyYSYppgFdAEVfgjMEoQGi9VaV23ondo'),
  },
  {
    symbol: 'DGRW',
    name: 'WisdomTree US Quality Dividend Growth Fund',
    logo: CB + 'wisdomtree.com',
    decimals: 9,
    mint: new PublicKey('gnoSQSNTNZHViqVfxCcPDVxcRA29mrJL7C6JqYLondo'),
  },
  {
    symbol: 'EEM',
    name: 'iShares MSCI Emerging Markets ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('916SDKz7y5ZcEZC9CtnQ5Djs1Y8Yv3UAPb6bak8ondo'),
  },
  {
    symbol: 'EFA',
    name: 'iShares MSCI EAFE ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('AbvryMGnaba9oADMZk8Vp2Av6MtczsncGyfWaC4ondo'),
  },
  {
    symbol: 'IEMG',
    name: 'iShares Core MSCI Emerging Markets ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('cdVNL9WXD2BTkbZhRZMVXPmVSiRo44hJWRtnaC8ondo'),
  },
  {
    symbol: 'IJH',
    name: 'iShares Core S&P MidCap ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('cfPLN9WXD2BTkbZhRZMVXPmVSiRo44hJWRtnaC8ondo'),
  },
  {
    symbol: 'ITOT',
    name: 'iShares Core S&P Total US Stock Market ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('CPWkMURVvcnX8hGjqCTb8i5LkzV3VSvyk7SeJi8ondo'),
  },
  {
    symbol: 'IWF',
    name: 'iShares Russell 1000 Growth ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('dSHPFuMMjZqt7xDYGWrexXTSkdEZAiZngqymQF2ondo'),
  },
  {
    symbol: 'IWN',
    name: 'iShares Russell 2000 Value ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('DX7g7WNjDpVzNK9CG81v7wb6ZbiNzYfkdzH2Xs5ondo'),
  },
  {
    symbol: 'PSQ',
    name: 'ProShares Short QQQ',
    logo: CB + 'proshares.com',
    decimals: 9,
    mint: new PublicKey('qKtU9A7ij34XmtxaSzYfxCpkgAZzzFsqnUb2kW2ondo'),
  },
  {
    symbol: 'SQQQ',
    name: 'ProShares UltraPro Short QQQ',
    logo: CB + 'proshares.com',
    decimals: 9,
    mint: new PublicKey('D1tu7Fnm3cCpKyyPXrqm5GXShPqMj7a2SEjjq9fondo'),
  },
  {
    symbol: 'TQQQ',
    name: 'ProShares UltraPro QQQ',
    logo: CB + 'proshares.com',
    decimals: 9,
    mint: new PublicKey('14W1itEkV7k1W819mLSknFTaMmkCtPokbF2tRkPUondo'),
  },
  {
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    logo: CB + 'vanguard.com',
    decimals: 9,
    mint: new PublicKey('jCCU4GwukjNxAXJowG2S4KCrr5g6YyUB61WHYvGondo'),
  },
  {
    symbol: 'VTV',
    name: 'Vanguard Value ETF',
    logo: CB + 'vanguard.com',
    decimals: 9,
    mint: new PublicKey('KuiYLPVq65qixD9TgvxBC576C4gG6vVTCdbh2zFondo'),
  },
  // Bonds
  {
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('KaSLSWByKy6b9FrCYXPEJoHmLpuFZtTCJk1F1Z9ondo'),
  },
  {
    symbol: 'HYG',
    name: 'iShares iBoxx $ High Yield Corporate Bond ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('c5ug15fwZRfQhhVa6LHscFY33ebVDHcVCezYpj7ondo'),
  },
  {
    symbol: 'SGOV',
    name: 'iShares 0-3 Month Treasury Bond ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('HjrN6ChZK2QRL6hMXayjGPLFvxhgjwKEy135VRjondo'),
  },
  {
    symbol: 'AGG',
    name: 'iShares Core US Aggregate Bond ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('13qTjKx53y6LKGGStiKeieGbnVx3fx1bbwopKFb3ondo'),
  },
  {
    symbol: 'BINC',
    name: 'iShares Flexible Income Active ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('mhZ69E1vDnAsQJXAwarLYSX5tmgeMajXBJ2rXAcondo'),
  },
  {
    symbol: 'CLOA',
    name: 'iShares AAA CLO Active ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('t71FyTYHVkPAb5g48adDHmkVxXYbUuP2eq6jDZLondo'),
  },
  {
    symbol: 'CLOI',
    name: 'VanEck CLO ETF',
    logo: CB + 'vaneck.com',
    decimals: 9,
    mint: new PublicKey('ucQ3VfWAx9pkCN4Kg84zE56FtB4FJN2kQH4ArYYondo'),
  },
  {
    symbol: 'JAAA',
    name: 'Janus Henderson AAA CLO ETF',
    logo: CB + 'janushenderson.com',
    decimals: 9,
    mint: new PublicKey('KZtqx9BJbpcGY7vdzhqPXM3ECKChxE5YhXaDiwRondo'),
  },
  {
    symbol: 'TIP',
    name: 'iShares TIPS Bond ETF',
    logo: CB + 'ishares.com',
    decimals: 9,
    mint: new PublicKey('k6BPp2Xmf2TYgrZiUyWfUoZBKeqaDbvPoAVgSx2ondo'),
  },
  {
    symbol: 'USFR',
    name: 'WisdomTree Floating Rate Treasury Fund',
    logo: CB + 'wisdomtree.com',
    decimals: 9,
    mint: new PublicKey('o6U1Sm6Vd7EofMyCrL28mrp2QLzgYGgjveHiEQ5ondo'),
  },
]
